name: eventurio
description: "A Community Events Hub where users can discover, create, and join local events with real-time updates, maps integration, and notifications."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.3
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
